export const contacts = {
  fullName_en: 'Kovalchuk Ihor',
  fullName_cs: 'Kovalčuk Ihor',
  fullName_de: 'Kovalchuk Ihor',
  fullName_pl: 'Kovalczuk Ihor',
  fullName_ua: 'Ковальчук Ігор',
  address_en: 'Jelenia Góra, Lower Silesia, Poland',
  address_cs: 'Jelení Hora, Dolnoslezské vojvodství, Polsko',
  address_de: 'Jelenia Góra, Niederschlesien, Polen',
  address_pl: 'Jelenia Góra, Dolnośląskie, Polska',
  address_ua: 'Єленя-Гура, Нижня Сілезія, Польща',
  facebook: '',
  facebookHandle: '',
  workingHours_en: 'Mon - Fri 08:00-18:00',
  workingHours_cs: 'Po - Pá 08:00-18:00',
  workingHours_de: 'Mo - Fr 08:00-18:00',
  workingHours_pl: 'Pn - Pt 08:00-18:00',
  workingHours_ua: 'Пн - Пт 08:00-18:00',
  phone: '+48 576 263 485',
  email: 'contact@ikomeble.com',
  businessCode: '6112831904',
  businessName: 'IKO MEBLE NA WYMIAR IHOR KOVALCHUK',
};
